packages:
  - "apps/*"
  - "packages/*"

overrides:
  "vite": "6.3.5"

catalog:
  "@astrojs/check": ^0.9.0
  "@tailwindcss/vite": "^4.1.14"
  astro: ^5.14.1
  tailwind-merge: ^3.3.1
  tailwindcss: "^4.1.14"
  typescript: ^5.3.0
