#+title:   Bits
#+startup: content

* What's in the box?
** Decision
#+begin_src sh :results output raw :exports output
fd --type file '\.org$' decisions | while read -r file; do
  title=$(awk -F':[[:space:]]*' 'NR==1 { print $2 }' "$file")
  echo "- [[file:$file][$title]]"
done
#+end_src

#+results:
- [[file:decisions/20251009133634-get-the-message-out.org][Get the message out]]
- [[file:decisions/20251009144920-python-style-environment-variables.org][Python-style environment variables]]

** Dev tasks
#+begin_src sh :results output verbatim
just
#+end_src

#+results:
#+begin_example
Available recipes:
    [dev]
    dev              # Fire up a local development environment
    fmt              # Format project files

    [docs]
    decide +title    # Create a new decision record

    [iac]
    apply dir        # Apply one or all Terraform projects
    init dir *args   # Initialize one or all Terraform projects
    output dir *args # Interact with outputs from the named Terraform project
    plan dir         # Plan one or all Terraform projects

    [setup]
    mkcert           # Create self-signed SSL certificates via mkcert
    setup            # Setup a local development environment
#+end_example

* Development
I would recommend installing [[https://devenv.sh][=devenv=]] to simplify setting up a working
development environment. With =devenv= installed, one can spin up a development
environment with a single command:

#+begin_src sh :eval never
devenv up
#+end_src

As we make use of the =invetica.dev= domain during development and generate
self-signed SSL certificates via =mkcert=, you'll want to run =just setup= the
first time you fire things up.

With a running development environment, one has access to the following:

1. [[https://land.invetica.dev][land.invetica.dev]]: Landing page where people can find out more about Bits.
1. [[https://edit.invetica.dev/][edit.invetica.dev]]: Admin panel for customizing your page.
2. [[https://*.page.invetica.dev/][*.page.invetica.dev]]: The Bits experience.

* Tests
** Development URLs
#+begin_src zsh :results output verbatim
urls=(
  https://edit.invetica.dev
  https://land.invetica.dev
  https://page.invetica.dev
)

for url in $urls; do
  http_code="$(curl --silent --output /dev/null --write-out "%{http_code}" "$url")"
  if [ "$http_code" -eq 200 ]; then
    echo "✅ $url"
  else
    echo "❌ $url ($http_code)"
  fi
done
#+end_src

#+results:
: ✅ https://edit.invetica.dev
: ✅ https://land.invetica.dev
: ✅ https://page.invetica.dev
