#+title:   Bits
#+startup: content

*Warning:* Bits supports creators who produce content some may consider explicit
or not suitable for work. You may encounter such content in our product research
and competitor analysis. This repo itself does not contain any sexually explicit
content.

Platforms control your audience. Payment processors control your revenue. Bits
gives you both back.

*What you get:*

- Subscriptions, one-time purchases, digital downloads
- Video hosting and delivery
- Your data, your domain, your rules
- Permissive content policies for persecuted creators

*Why it works:*

- Self-host on a $5/month VPS or use managed hosting
- Single binary deployment - no complex setup
- Built with care to minimize resource usage and maximize reliability
- Open source - audit the code, modify what you need, contribute back

*The model:* Like WordPress.org - free to self-host, managed option available.
You're never locked in.

*Current state:* Active development. Your funding accelerates delivery.

* Development
Start required services and spawn a Tailwind watcher via =devenv=:

#+begin_src sh :eval never
devenv up
#+end_src

Then one can start an hot-reloading development process via Dioxus like so:

#+begin_src sh :eval never
just serve
#+end_src

** HTTPS and =*.test= URLs
*** Setup
To get our =*.test= URLs to work takes some effort with DNS.

#+begin_src sh :results output table :colnames '("Host" "Address")
drill bits.test | awk '/^bits/ { print $1 "\t" $5 }'
#+end_src

#+results:
| Host       |   Address |
|------------+-----------|
| bits.test. | 127.0.0.1 |

#+begin_src sh :results output verbatim
cat /etc/resolver/test
#+end_src

#+results:
: nameserver 10.10.10.254

*** Test
#+begin_src sh :results output verbatim :shebang "#!/usr/bin/env zsh"
urls=(
  https://www.usebits.app.test
  https://bits.page.test
  https://jcf.bits.page.test
)

for url in $urls; do
  http_code="$(curl --silent --output /dev/null --write-out "%{http_code}" "$url")"
  if [ "$http_code" -eq 200 ]; then
    echo "✅ $url"
  else
    echo "❌ $url ($http_code)"
  fi
done
#+end_src

#+results:
: ✅ https://www.usebits.app.test
: ✅ https://bits.page.test
: ✅ https://jcf.bits.page.test

And with a non-existent tenant, we expect a 404 response:

#+begin_src sh :results output verbatim
url="https://foo.bits.page.test"
http_code="$(curl --silent --output /dev/null --write-out "%{http_code}" "$url")"

if [ "$http_code" -eq 404 ]; then
  echo "✅ $url"
else
  echo "❌ $url ($http_code)"
fi
#+end_src

#+results:
: ❌ https://foo.bits.page.test (200)

** Decision records
#+begin_src sh :results output raw :exports output :exports results
fd --type file '\.org$' decisions | while read -r file; do
  title=$(awk -F':[[:space:]]*' 'NR==1 { print $2 }' "$file")
  echo "- [[file:$file][$title]]"
done
#+end_src

#+results:
- [[file:decisions/20251009133634-get-the-message-out.org][Get the message out]]
- [[file:decisions/20251009144920-python-style-environment-variables.org][Python-style environment variables]]
- [[file:decisions/20251118100535-mission-over-saas-startup-playbook.org][Mission over SaaS startup playbook]]
- [[file:decisions/20251119230950-ci-can-wait.org][CI can wait]]

** Dev tasks
#+begin_src sh :results output verbatim :exports results
just --list
#+end_src

#+results:
#+begin_example
Available recipes:
    [dev]
    build            # Build fullstack web packages
    check            # Run checks
    clean            # Clear build caches
    colo             # Run Dioxus in co-located mode
    dev              # Run Dioxus in co-located mode
    fix              # Fix errors within Bits
    fmt              # Format project files
    integrate        # Run integration tests
    lint             # Run lints
    mkcert           # Create self-signed SSL certificates via mkcert
    push             # Verify and push changes
    release
    setup            # Setup a local development environment
    solo             # Run Dioxus in solo mode
    tailwind dir     # Watch source code for Tailwind classes
    test             # Run unit and integration tests
    unit             # Run units tests
    www              # Run the marketing site

    [docs]
    decide +title    # Create a new decision record

    [iac]
    apply dir        # Apply one or all Terraform projects
    init dir *args   # Initialize one or all Terraform projects
    output dir *args # Interact with outputs one or all Terraform projects
    plan dir         # Plan one or all Terraform projects

    [postgres]
    db-destroy       # Delete all development PostgreSQL state
    migrate          # Run database migrations
    migration name   # Create a new migration
    psql *args       # Start an interactive psql session connected to the local development database
    seed             # Seed the database with test data
#+end_example

** SLOC
#+begin_src sh :results output verbatim :exports results
tokei
echo
echo "$(git describe --always --dirty --abbrev=7) @ $(date +"%Y/%m/%d %H:%M")"
#+end_src

#+results:
#+begin_example
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Language              Files        Lines         Code     Comments       Blanks
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Astro                    10          165          139            0           26
 CSS                       3           12           12            0            0
 HCL                      12          389          323           13           53
 HTML                      3           33           33            0            0
 JavaScript                2           51           43            1            7
 JSON                      4           58           58            0            0
 Just                      1          241          142           54           45
 MDX                       1           56            0           39           17
 Nix                       3          305          249            9           47
 Org                       8         1628         1477            4          147
 SQL                       2          115           98            1           16
 TOML                     13          319          271            2           46
 TypeScript                3           36           30            1            5
 YAML                      3         5046         3963            0         1083
─────────────────────────────────────────────────────────────────────────────────
 Markdown                  1           64            0           40           24
 |- Rust                   1          109           76           19           14
 (Total)                              173           76           59           38
─────────────────────────────────────────────────────────────────────────────────
 Rust                     29         2308         1966           29          313
 |- Markdown               8           29            0           28            1
 (Total)                             2337         1966           57          314
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Total                    98        10964         8880          240         1844
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

d68d58e-dirty @ 2025/12/01 12:25
#+end_example

* Tasks
** Setup                                                          :NOEXPORT:
#+begin_src emacs-lisp
(setq sql-postgres-program (executable-find "psql"))
#+end_src

#+results:
: /nix/store/19v6sifj4i7zynjb3r974yhqlx07lppm-postgresql-and-plugins-17.6/bin/psql

** Seed the database
We have a file:seeds.toml file that contains tenants and users we want to insert
immediately to speed up development.

#+begin_src sh :results output verbatim :eval query
just seed
#+end_src

#+property: header-args:sql  :engine postgresql
#+property: header-args:sql+ :dbhost     "localhost"
#+property: header-args:sql+ :database   "bits_dev"
#+property: header-args:sql+ :dbuser     "bits"
#+property: header-args:sql+ :dbpassword "please"
#+begin_src sql
select
  t.id,
  t.name,
  td.domain
from tenants t
join tenant_domains td on td.tenant_id = t.id;
#+end_src

#+results:
| id | name                             | domain                  |
|----+----------------------------------+-------------------------|
|  1 | Building Bits                    | jcf.bits.page.test      |
|  2 | Jimmy's Leather Emporium         | emporium.bits.page.test |
|  3 | Charlie's Countryside Adventures | charlie.bits.page.test  |
|  4 | Millie's Meat Treats             | milly.bits.page.test    |

** Truncate tables
To test empty states, one needs to truncate appropriate tables:

#+begin_src sh :results output verbatim :eval query
just psql 2>&1 <<SQL
  truncate table tenants;
SQL
#+end_src

** Verify email address
#+begin_src sh :results output verbatim :eval query
email="$(git config user.email)"

just psql 2>&1 <<SQL
  insert into email_verifications (email_address_id)
  values ((select id from email_addresses where address = '${email}'))
SQL
#+end_src

#+results:
: PGPASSWD=please psql --host=localhost --port=5432 --username=bits --dbname=bits_dev
: INSERT 0 1
: Time: 6.540 ms

* TODOs
#+begin_src sh :results output verbatim :exports results
rg --glob '!README.org' 'TODO|FIXME' </dev/null | sort
#+end_src

#+results:

* Troubleshooting
** Dioxus version
One needs to ensure Dioxus and =dioxus-cli= remain in sync or one might
encounter errors inside of =link= tags:

#+begin_src html :eval never
<link rel="stylesheet" href="/assets/This should be replaced by dx as part of the build process. If you see this error, make sure you are using a matching version of dx and dioxus and you are not stripping symbols from your binary."></link>
#+end_src

#+begin_src sh :results output table :colnames '("Package" "Version") :exports results
echo -e "dioxus\t$(grep 'dioxus = ' Cargo.toml | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')"
echo -e "dioxus-cli\t$(grep 'version = ' nix/overlays/dioxus-cli.nix | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')"
echo -e "wasm-bindgen-cli\t$(grep 'version = ' nix/overlays/wasm-bindgen-cli.nix | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')"
#+end_src

#+results:
| Package          | Version |
|------------------+---------|
| dioxus           |   0.7.1 |
| dioxus-cli       |   0.7.1 |
| wasm-bindgen-cli | 0.2.105 |
