#+title:   Bits
#+startup: content

Platforms control your audience. Payment processors control your revenue. Bits
gives you both back.

*What you get:*

- Subscriptions, one-time purchases, digital downloads
- Video hosting and delivery
- Your data, your domain, your rules
- Permissive content policies for persecuted creators

*Why it works:*

- Self-host on a $5/month VPS or use managed hosting
- Single binary deployment - no complex setup
- Built with care to minimize resource usage and maximize reliability
- Open source - audit the code, modify what you need, contribute back

*The model:* Like WordPress.org - free to self-host, managed option available.
You're never locked in.

*Current state:* Active development. Your funding accelerates delivery.

* Development
Start required services and spawn a Tailwind watcher via =devenv=:

#+begin_src sh :eval never
devenv up
#+end_src

Then one can start an hot-reloading development process via Dioxus like so:

#+begin_src sh :eval never
just serve
#+end_src

** Dioxus version
One needs to ensure Dioxus and =dioxus-cli= remain in sync or one might
encounter errors inside of =link= tags:

#+begin_src html :eval never
<link rel="stylesheet" href="/assets/This should be replaced by dx as part of the build process. If you see this error, make sure you are using a matching version of dx and dioxus and you are not stripping symbols from your binary."></link>
#+end_src

#+begin_src sh :results output table :colnames '("Package" "Version") :exports results
echo -e "dioxus\t$(grep 'dioxus = ' Cargo.toml | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')"
echo -e "dioxus-cli\t$(grep 'version = ' nix/overlays/dioxus-cli.nix | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')"
echo -e "wasm-bindgen-cli\t$(grep 'version = ' nix/overlays/wasm-bindgen-cli.nix | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')"
#+end_src

#+results:
| Package          | Version |
|------------------+---------|
| dioxus           |   0.7.1 |
| dioxus-cli       |   0.7.1 |
| wasm-bindgen-cli | 0.2.105 |

** HTTPS and =*.test= URLs
*** Setup
To get our =*.test= URLs to work takes some effort with DNS.

#+begin_src sh :results output table :colnames '("Host" "Address")
drill bits.test | awk '/^bits/ { print $1 "\t" $5 }'
#+end_src

#+results:
| Host       |   Address |
|------------+-----------|
| bits.test. | 127.0.0.1 |

#+begin_src sh :results output verbatim
cat /etc/resolver/test
#+end_src

#+results:
: nameserver 10.10.10.254

*** Test
#+begin_src sh :results output verbatim :shebang "#!/usr/bin/env zsh"
urls=(
  https://www.usebits.app.test
  https://bits.page.test
  https://jcf.bits.page.test
)

for url in $urls; do
  http_code="$(curl --silent --output /dev/null --write-out "%{http_code}" "$url")"
  if [ "$http_code" -eq 200 ]; then
    echo "✅ $url"
  else
    echo "❌ $url ($http_code)"
  fi
done
#+end_src

#+results:
: ✅ https://www.usebits.app.test
: ❌ https://bits.page.test (502)
: ❌ https://jcf.bits.page.test (502)

And with a non-existent tenant, we expect a 404 response:

#+begin_src sh :results output verbatim
url="https://foo.bits.page.test"
http_code="$(curl --silent --output /dev/null --write-out "%{http_code}" "$url")"

if [ "$http_code" -eq 404 ]; then
  echo "✅ $url"
else
  echo "❌ $url ($http_code)"
fi
#+end_src

#+results:
: ❌ https://foo.bits.page.test (502)

** Decision records
#+begin_src sh :results output raw :exports output :exports results
fd --type file '\.org$' decisions | while read -r file; do
  title=$(awk -F':[[:space:]]*' 'NR==1 { print $2 }' "$file")
  echo "- [[file:$file][$title]]"
done
#+end_src

#+results:
- [[file:decisions/20251009133634-get-the-message-out.org][Get the message out]]
- [[file:decisions/20251009144920-python-style-environment-variables.org][Python-style environment variables]]
- [[file:decisions/20251118100535-mission-over-saas-startup-playbook.org][Mission over SaaS startup playbook]]
- [[file:decisions/20251119230950-ci-can-wait.org][CI can wait]]

** Dev tasks
#+begin_src sh :results output verbatim :exports results
just --list
#+end_src

#+results:
#+begin_example
Available recipes:
    [dev]
    build            # Build fullstack web packages
    check            # Run checks
    clean            # Clear build caches
    fix              # Fix errors within Bits
    fmt              # Format project files
    integration      # Run integration tests
    lint             # Run lints
    mkcert           # Create self-signed SSL certificates via mkcert
    multi            # Run Dioxus in multi-tenant mode
    push             # Verify and push changes
    release
    serve            # Run Dioxus in single-tenant mode
    setup            # Setup a local development environment
    tailwind dir     # Watch source code for Tailwind classes
    test             # Run tests
    www              # Run the marketing site

    [docs]
    decide +title    # Create a new decision record

    [iac]
    apply dir        # Apply one or all Terraform projects
    init dir *args   # Initialize one or all Terraform projects
    output dir *args # Interact with outputs one or all Terraform projects
    plan dir         # Plan one or all Terraform projects

    [postgres]
    migrate          # Run database migrations
    migration name   # Create a new migration
    psql *args       # Start an interactive psql session connected to the local development database
#+end_example

** SLOC
#+begin_src sh :results output verbatim :exports results
tokei
echo
echo "$(git describe --always --dirty --abbrev=7) @ $(date +"%Y/%m/%d %H:%M")"
#+end_src

#+results:
#+begin_example
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Language              Files        Lines         Code     Comments       Blanks
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Astro                    10          165          139            0           26
 CSS                       8         1556         1552            4            0
 HCL                      12          389          323           13           53
 HTML                      3           33           33            0            0
 JavaScript                2           51           43            1            7
 JSON                      4           58           58            0            0
 Just                      1          207          121           48           38
 MDX                       1           56            0           39           17
 Nix                       3          299          244            9           46
 Org                       8         1550         1410            4          136
 SQL                       2          114           97            1           16
 TOML                     13          269          230            0           39
 TypeScript                3           36           30            1            5
 YAML                      3         5046         3963            0         1083
─────────────────────────────────────────────────────────────────────────────────
 Markdown                  1           36            0           23           13
 |- Rust                   1           68           49           10            9
 (Total)                              104           49           33           22
─────────────────────────────────────────────────────────────────────────────────
 Rust                     19         1433         1230            5          198
 |- Markdown               6           16            0           16            0
 (Total)                             1449         1230           21          198
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Total                    93        11382         9522          174         1686
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

c5dc45c-dirty @ 2025/11/26 15:21
#+end_example

** TODOs
#+begin_src sh :results output verbatim :exports results
rg --glob '!README.org' 'TODO|FIXME' </dev/null | sort
#+end_src

#+results:
: crates/bits-e2e/tests/solo.rs:    // TODO: Assert no marketing content present
