# https://opentelemetry.io/docs/zero-code/java/agent/configuration/

otel.exporter.otlp.protocol=grpc

# Exporters
otel.logs.exporter=none
otel.metrics.exporter=otlp
otel.traces.exporter=otlp

otel.instrumentation.executors.enabled=false
otel.instrumentation.hikaricp.enabled=true
otel.instrumentation.java-http-client.enabled=true
otel.instrumentation.jdbc-datasource.enabled=true
otel.instrumentation.jdbc.enabled=true
otel.instrumentation.runtime-telemetry.enabled=false
